---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: httpd-daemon
  labels:
    type: webserver
spec:
  selector:
    matchLabels:
      type: webserver
  template:
    metadata:
      name: httpd-pod
      labels:
        type: webserver
    spec:
      containers:
        - name: myhttpd
          image: httpd

...
