---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    types: db
    author: ashu
spec:
  containers:
    - name: mypostgres
      image: postgres
      env:
        - name:  POSTGRES_PASSWORD
          value: intelliqit
        - name: POSTGRES_USER
          value: myuser
        - name: POSTGRES_DB
          value: mydb


...
