---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  labels:
    type: webserver
    author: ashu
spec:
  containers:
    - name: apache
      image: httpd
      ports:
        - containerPort: 80
          hostPort: 8080
...
