---
apiVersion: v1
kind: Pod
metadata:
  name: tomcat-pod
  namespace: test-ns
  labels:
    type: webserver
    author: ashu
spec:
  containers:
    - name: tomcat
      image: tomee
      ports:
        - containerPort: 8080
          hostPort: 8080
...
