---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
    type: appserver
    author: ashu
spec:
  replicas: 3
  selector:
    matchLabels:
      type: appserver
  template:
    metadata:
      name: httpd-pod
      labels:
        type: appserver
    spec:
      containers:
        - name: myhttpd
          image: httpd
          ports:
            - containerPort: 8080
              hostPort: 8080


...
