---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  labels:
    type: app
    author: ashu
spec:
  replicas: 3
  selector:
    matchLabels:
      type: app
  template:
    metadata:
      name: tomcat-pod
      labels:
        type: app
    spec:
      containers:
        - name: mytomcat
          image: tomee
          ports:
            - containerPort: 8080
              hostPort: 8080

...
