---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  labels:
    author: ashu
spec:
  type: LoadBalancer
  ports:
    - targetPort: 8080
      port: 8080
  selector:
    type: jenkins-pod
    author: ashu

...
